### ISSUE TITLE
Black-Jack : 게임 도중에 전적초기화 버튼을 누르고 취소 클릭 시 배팅액을 잃지않고 패배하지않는 현상

### ISSUE THREAD

**Issue by dition0221** [dition0221/Casino_Games#1]
- Issue : Black-Jack
    - 게임 도중에 전적초기화 버튼을 누르고 취소 클릭 시 배팅액을 잃지않고 패배하지않는 현상
      - play 버튼을 누르면 전적초기화 버튼을 비활성화 + 게임이 끝났을 때 다시 활성화 하도록 수정할 것

**Comment by dition0221** [comment]
23-05-27
- 문제 해결
- HTML에서 비활성화(disabled)
- JavaScript에서 게임 중 일 때만 'isPlaying'변수를 true 값으로 주어, 조건문으로 비활성화

**Comment by dition0221** [comment]
23-05-27
- 문제 해결
- HTML에서 비활성화(disabled)
- JavaScript에서 게임 중 일 때만 'isPlaying'변수를 true 값으로 주어, 조건문으로 비활성화

**Comment by wychoi-controlf** [comment]
@dition0221 안녕하세요. 혹시 개발에 관해서 연락 드리고 싶은데, 괜찮을까요?

**Comment by dition0221** [comment]
@wychoi-controlf  무슨 일 이시죠?
